doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            contact_list_id: App\Infrastructure\Persistence\Doctrine\ContactList\ContactListIdType
            contact_id: App\Infrastructure\Persistence\Doctrine\Contact\ContactIdType
            contact_name: App\Infrastructure\Persistence\Doctrine\Contact\ContactNameType
            contact_surname: App\Infrastructure\Persistence\Doctrine\Contact\ContactSurnameType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Contact:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Contact'
                prefix: 'App\Domain\Contact'
            App\ContactList:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/ContactList'
                prefix: 'App\Domain\ContactList'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
