contacts_create:
    path: /contacts/
    controller: App\Infrastructure\Controller\Contacts\ContactsPostController
    methods: [ POST ]

contacts_confirm:
    path: /contacts/
    controller: App\Infrastructure\Controller\Contacts\ContactsPutController
    methods: [ PUT ]
