name: PHP Coding Standards Fixer

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:

            -   name: Check-out the code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    version: 2
                    php_version: 8.1

            -   name: Check src folder
                run: php ./vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no ./src

            -   name: Check tests folder
                run: php ./vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no ./tests

            -   name: Check lib folder
                run: php ./vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no ./lib
